//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinHoaDon
    {
        public string IDHoaDon { get; set; }
        public string LoaiBan { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public string IDDatMon { get; set; }
        public string TenMon { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiaMon { get; set; }
        public string IDNguoiDung { get; set; }
        public string IDCustommer { get; set; }
        public string Note { get; set; }
        public string IDThongTin { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
